In [1]:
# Name: example_basics.ipynb
# Authors: Stephan Meighen-Berger
# Basic example for the package, includes the typically used options
# For a full list of options, please check the config file

In [2]:
# General imports
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import sys
import pickle
from numpy import linalg as LA
import pandas as pd
pd.set_option('display.max_rows', None)
%matplotlib inline

In [3]:
# Adding path to module
sys.path.append("../")
# picture path
PICS = '../pics/'

In [4]:
# Module imports
from fourth_day import Fourth_Day, config

In [5]:
# POM_properties=config["geometry"]['detector properties']['POM']
# x_coords=POM_properties['x_offsets']*10
# y_coords=POM_properties['y_offsets']*10
# z_coords=POM_properties['z_offsets']*10
# xyz_coords=np.stack((x_coords,y_coords,z_coords),axis=-1)
# #np.asarra([0,0,0])-xyz_coords
# xyz_coords=np.column_stack((x_coords,y_coords,z_coords))

In [6]:
# xyz_coords

In [7]:
# xyz_coords[:,-1]+=25

In [8]:
# xyz_coords

In [9]:
# norm_xyz_coords=[]
# for vec in xyz_coords:
#     magnitude = np.linalg.norm(vec)
#     normalized_vector = vec / magnitude
#     norm_xyz_coords.append(normalized_vector)

In [10]:
# fig = plt.figure()
# ax = fig.add_subplot(111, projection='3d')

# for vec in xyz_coords:
#     ax.quiver(0,0,0,vec[0],vec[1],vec[2],length = 1,normalize = True)
    
# det=0
# ax.scatter(norm_xyz_coords[det][0],norm_xyz_coords[det][1],norm_xyz_coords[det][2],color='red')

# ax.set_xlim([-3,3])
# ax.set_ylim([-1,1])
# ax.set_zlim([-1,1])
# ax.set_xlabel("X")
# ax.set_ylabel("Y")
# ax.set_zlabel("Z")
# ax.view_init(45,-45)

In [11]:
# ---------------------------------------------
# Some example settings
# For a full lost check the config file
rs = np.random.randint(1300, 1400)
config['general']['random state seed'] = rs
print("Random Seed:", rs)
# ---------------------------------------------
# Scenario Settings
# These are general settings pertaining to the simulation run
config['scenario']['population size'] = 10  # The starting population size
config['scenario']['duration'] = 300 * 1  # Total simulation time in seconds
config['scenario']['exclusion'] = False  # If an exclusion zone should be used (the detector)
config['scenario']['injection']['rate'] = 1  #  Injection rate in per second, a distribution is constructed from this value
config['scenario']['injection']['y range'] = [0., 10.]  # The y-range of injection
# config['scenario']['light prop'] = {  # Where the emitted light should be propagated to (typically the detector location)
#             "switch": True,  # If light should be propagated
#             "x_pos": 3.,  # The x-coordinates
#             "y_pos": 0.5 * 15. - 0.15,  # The y-coordinates
#         }
config['scenario']['detector'] = {  # detector specific properties, positions are defined as offsets from the light prop values
    "switch": True,  # If the detector should be modelled
    "type": "POM",  # Detector name, implemented types are given in the config
    "response": True,  # If a detector response should be used
    "acceptance": "Flat",  # Flat acceptance
    "mean detection prob": 1.  # Used for the acceptance calculation
}
# ---------------------------------------------
# Organisms
# Organisms properties are defined here
config['organisms']['emission fraction'] = 0.1  # Amount of energy an organism uses per pulse
config['organisms']['alpha'] = 1e0  # Proportionality factor for the emission probability
config['organisms']["minimal shear stress"] = 0.005  # The minimal amount of shear stress needed to emit (generic units)
config["organisms"]["filter"] = 'depth'  # Method of filtering organisms (here depth)
config["organisms"]["depth filter"] = 10000.  # Organisms need to exist below this depth
# ---------------------------------------------
# Geometry
#These settings define the geometry of the system
#Typically a box (simulation volume) with a spherical exclusion zone (detector)
config['geometry']['volume'] = {
    'function': 'rectangle',
    'x_length': 30.,
    'y_length': 20.,
#    "z_length": 10.,
    'offset': None,
}
# Reduce the observation size to reduce the computational load
config['geometry']['observation'] = {
    'function': 'rectangle',
    'x_length': 30.,
    'y_length': 20.,
#    "z_length": 10.,
    "offset": np.array([0., 0.]),
}
# The detector volume
config['geometry']["exclusion"] = {
    "function": "sphere",
    "radius": 0.3,
    "x_pos": 15.,
    "y_pos": 10.,
#    "z_pos": 10.,
}
# ---------------------------------------------
# Water
# Properties of the current model
config['water']['model']['name'] = 'custom'  # Use a custom (non analytic) model
config['water']['model']['off set'] = np.array([0., 0.])  # Offset of the custom model
config['water']['model']['directory'] = "Parabola_5mm/run_10cm_npy/"  # The files used by the custom model
config['water']['model']['time step'] = 1.  # in Seconds

Random Seed: 1358


In [12]:
# Creating a fourth_day object
# Use this to interact with with the module
fd = Fourth_Day()

In [13]:
# Use this method if you need to download files.
# fd.load_data()

In [ ]:
# Launching solver
# This might take a while depending on the settings
# Check the log file (standard setting is in the run folder) for the current iteration
fd.sim()

Lower detector!
tip_coords_copy: [[ 0.53729961  0.84339145 10.        ]
 [ 0.          0.84339145  9.46270039]
 [-0.53729961  0.84339145 10.        ]
 [ 0.          0.84339145 10.53729961]
 [ 0.64085638  0.42261826  9.35914362]
 [-0.64085638  0.42261826  9.35914362]
 [-0.64085638  0.42261826 10.64085638]
 [ 0.64085638  0.42261826 10.64085638]
 [ 0.53729961 -0.84339145 10.        ]
 [ 0.         -0.84339145  9.46270039]
 [-0.53729961 -0.84339145 10.        ]
 [ 0.         -0.84339145 10.53729961]
 [ 0.64085638 -0.42261826  9.35914362]
 [-0.64085638 -0.42261826  9.35914362]
 [-0.64085638 -0.42261826 10.64085638]
 [ 0.64085638 -0.42261826 10.64085638]]
path length []
testing detector num with coord 0 [ 0.53729961  0.84339145 10.        ]
emission is at []
testing detector num with coord 1 [0.         0.84339145 9.46270039]
emission is at []
testing detector num with coord 2 [-0.53729961  0.84339145 10.        ]
emission is at []
testing detector num with coord 3 [ 0.          0.84339145 1

path length [[51.47610972 60.20731001]
 [51.88129772 60.61960259]
 [51.24389045 59.98652315]
 [50.83362202 59.56984909]
 [52.10277211 60.83127733]
 [51.82902534 60.57055733]
 [50.57563931 59.31530831]
 [50.85613322 59.58152135]
 [51.41509588 60.13147379]
 [51.82076096 60.5442828 ]
 [51.1825998  59.91040745]
 [50.7718361  59.4932003 ]
 [52.07257533 60.79367812]
 [51.79866898 60.53279618]
 [50.54453018 59.27674753]
 [50.82519578 59.54313298]]
testing detector num with coord 0 [ 0.53729961  0.84339145 10.        ]
emission is at [[ 3.90118172  8.13912419 60.07072569]
 [ 2.6525039   7.29483884 68.70528079]]
sphere center [15. 10. 10.]
testing detector num with coord 1 [0.         0.84339145 9.46270039]
emission is at [[ 3.90118172  8.13912419 60.07072569]
 [ 2.6525039   7.29483884 68.70528079]]
sphere center [15. 10. 10.]
testing detector num with coord 2 [-0.53729961  0.84339145 10.        ]
emission is at [[ 3.90118172  8.13912419 60.07072569]
 [ 2.6525039   7.29483884 68.70528079]]
sphe

path length [[51.29810311 60.04660043 54.00638115]
 [51.71371395 60.46686057 54.41230207]
 [51.08335457 59.83910873 53.77502656]
 [50.66257283 59.41440843 53.36425837]
 [51.92349259 60.67089758 54.63440672]
 [51.67035201 60.4258899  54.3615367 ]
 [50.41302115 59.16757182 53.10792562]
 [50.67244327 59.41776837 53.38720342]
 [51.23001744 59.97054842 53.94933439]
 [51.64617619 60.39133781 54.35568132]
 [51.01498229 59.76279268 53.71773411]
 [50.59363191 59.33754616 53.30652443]
 [51.88979764 60.6331927  54.60615715]
 [51.63649188 60.38803204 54.33314526]
 [50.37831595 59.12890831 53.07886364]
 [50.63791587 59.37926778 53.35829355]]
testing detector num with coord 0 [ 0.53729961  0.84339145 10.        ]
emission is at [[ 4.77001457  7.93076639 60.07072569]
 [ 3.42578293  7.29439249 68.70528079]
 [ 3.39766357  8.17447632 62.55659173]]
sphere center [15. 10. 10.]
testing detector num with coord 1 [0.         0.84339145 9.46270039]
emission is at [[ 4.77001457  7.93076639 60.07072569]
 [ 3.42

path length [[51.17065509 59.90669694 53.57132695 53.828045  ]
 [51.59445139 60.33388159 53.98618367 54.24342377]
 [50.96986327 59.71074358 53.3544218  53.61235932]
 [50.54082992 59.27906857 52.9346141  53.19205277]
 [51.79449945 60.53233976 54.20383416 54.45655908]
 [51.55781591 60.30097099 53.94805671 54.20218759]
 [50.29767197 59.03999058 52.69049253 52.94480362]
 [50.54025719 59.27628144 52.95234477 53.20518695]
 [51.0954525  59.8347081  53.52944747 53.7707733 ]
 [51.51986741 60.26240306 53.94462626 54.1865911 ]
 [50.89436398 59.63851821 53.31237192 53.55485697]
 [50.46468877 59.2063166  52.89223047 53.13409556]
 [51.75728376 60.49665036 54.18309763 54.42819951]
 [51.52042926 60.26514458 53.92722183 54.17369486]
 [50.25934793 59.00339851 52.66916018 52.91563386]
 [50.50211725 59.23983533 52.93111796 53.17616001]]
testing detector num with coord 0 [ 0.53729961  0.84339145 10.        ]
emission is at [[ 5.45738153  7.72031235 60.07072569]
 [ 4.09386901  7.44482677 68.70528079]
 [ 4.2

path length [[51.06096276 59.74595184 53.40429297 53.66953994 36.32335556]
 [51.49206619 60.18122102 53.82854107 54.09373435 36.65596687]
 [50.87270308 59.56350113 53.20310612 53.46859011 35.98062003]
 [50.43630592 59.12368447 52.77383041 53.03939621 35.64170689]
 [51.68390238 60.37412    54.03744175 54.29887996 36.92697081]
 [51.46199733 60.15871329 53.80021663 54.0619043  36.52456466]
 [50.19944814 58.89468711 52.53911389 52.8011798  35.30697022]
 [50.42690937 59.11469996 52.78200726 53.04378811 35.72309471]
 [50.98153815 59.6826645  53.3632655  53.61392618 36.21814112]
 [51.41330757 60.11839189 53.7878372  54.03855715 36.55170986]
 [50.79298409 59.50001973 53.16192338 53.41276712 35.87440041]
 [50.35589607 59.05973032 52.73231241 52.98312102 35.5344742 ]
 [51.64459852 60.34274554 54.017128   54.27134253 36.87514906]
 [51.42252387 60.12722642 53.77981327 54.0342461  36.47217114]
 [50.1589811  58.86252409 52.5182206  52.77286086 35.25276714]
 [50.38662502 59.08265671 52.76121015 53.01

path length [[50.95734634 59.62265634 53.24751389 53.52255395 36.13678983 65.47837091
  38.21410865]
 [51.39554249 60.06483187 53.68118372 53.95539984 36.48167937 65.9081128
  38.54766194]
 [50.78130074 59.45197732 53.0622896  53.33621676 35.81381916 65.28525893
  37.87058767]
 [50.33775782 59.00520934 52.62351972 52.89830458 35.46243494 64.85138979
  37.53101743]
 [51.57991239 60.25191799 53.88129347 54.15281889 36.73581487 66.11742326
  38.83299189]
 [51.37241189 60.05042056 53.66290563 53.9330912  36.35661398 65.88926067
  38.42950818]
 [50.10760548 58.78406582 52.39849827 52.66928343 35.13319944 64.62651584
  37.20987767]
 [50.32032181 58.98988902 52.6221338  52.89426137 35.52546153 64.85912069
  37.62644225]
 [50.87601306 59.56314422 53.20782536 53.46945086 36.0080047  65.45568573
  38.16363657]
 [51.31490375 60.00575829 53.64181605 53.90272318 36.35411604 65.88557559
  38.49762717]
 [50.69968504 59.39229418 53.02246243 53.28292797 35.68386843 65.26250663
  37.81965715]
 [50.25542

path length [[50.86956192 55.79457097 59.5155877  53.10088105 53.38388257 35.87156815
  65.32879611 37.94337653 68.81737482]
 [51.31398516 56.24842035 59.96424372 53.54404779 53.82546954 36.23232286
  65.76625217 38.29107609 69.24924514]
 [50.70429855 55.64610958 59.3560997  52.93195519 53.21248801 35.57336644
  65.14884245 37.62137986 68.62857076]
 [50.25448385 55.18730715 58.90281171 52.48362026 52.76577135 35.20586006
  64.7072125  37.26743265 68.19276977]
 [51.49205326 56.41160884 60.14543653 53.7352071  54.01498045 36.47158867
  65.96797254 38.56433033 69.4456824 ]
 [51.29726861 56.23643154 59.95715911 53.5360493  53.81288683 36.12153853
  65.75536521 38.18620704 69.22247392]
 [50.03056256 54.96817362 58.68879206 52.26857329 52.54618807 34.88988204
  64.48999868 36.95854847 67.95999404]
 [50.23025954 55.14737972 58.88112533 52.47254198 52.75313455 35.25216452
  64.70676378 37.34910268 68.18733533]
 [50.78774629 55.69112174 59.45824122 53.06275802 53.3333997  35.73852619
  65.30593

path length [[50.79077469 55.70358282 59.42629503 52.98151476 53.26941394 35.6624227
  59.9295169  65.20757048 37.72449058 68.69853902]
 [51.24106907 56.16432617 59.88078697 53.43305507 53.71876817 36.03569788
  60.369435   65.65167527 38.08438719 69.13626594]
 [50.63575416 55.5673286  59.27700615 52.82714438 53.11145922 35.383697
  59.75605386 65.0390737  37.42137002 68.51972832]
 [50.18002824 55.10159356 58.81784891 52.37038014 52.6569227  35.0034696
  59.31158644 64.590757   37.05503442 68.07803731]
 [51.41321686 56.32039596 60.05630221 53.61617411 53.90109006 36.26525263
  60.54952875 65.84675224 38.34688127 69.32709511]
 [51.23051097 56.15962768 59.88007071 53.43418675 53.71485402 35.93813497
  60.34470167 65.64768723 37.99098401 69.11570765]
 [49.96211243 54.88959518 58.61003543 52.16423576 52.44578757 34.69996928
  59.08026276 64.38020438 36.75680567 67.85124125]
 [50.1494396  55.05407233 58.79007416 52.35063807 52.63651395 35.03864825
  59.28945825 64.58317628 37.12453636 68.06

path length [[50.04135477 50.70798159 55.60996406 54.925235   59.34171273 52.8712161
  53.1622931  35.51383597 59.81238226 65.09452754 37.52047433 68.60201263]
 [50.51259898 51.16455162 56.07824956 55.39259767 59.80212589 53.33116541
  53.61949285 35.89587999 60.25956975 65.54521582 37.89244079 69.04464103]
 [49.92448094 50.5639334  55.48717079 54.80083194 59.20287454 52.7316438
  53.01807309 35.24864846 59.65153832 64.9374818  37.23631523 68.43160578]
 [49.44763219 50.10189035 55.01385418 54.32837881 58.73776437 52.26641891
  52.55564164 34.8595118  59.19975802 64.48254602 36.85772778 67.98498622]
 [50.65764234 51.33084532 56.22666806 55.54205951 59.97168306 53.50604929
  53.7943871  36.12012306 60.43225768 65.73364996 38.14411786 69.23095637]
 [50.51991224 51.16107906 56.08178782 55.39529967 59.80779306 53.34151574
  53.62435384 35.8089544  60.24233807 65.54811908 37.81053632 69.02950958]
 [49.24723003 49.89091535 54.80995169 54.12362616 58.53618963 52.0693046
  52.35309366 34.566161

path length [[49.9705433  50.62620295 55.52783795 54.84259501 59.26141771 52.77062275
  53.06260212 35.36304481 59.70042674 64.98953976 37.33120021 68.5041609 ]
 [50.44874509 51.08918101 56.00357302 55.31748226 59.72785075 53.23898882
  53.52776563 35.75492424 60.15496586 65.44674493 37.71508185 68.95187198]
 [49.86624346 50.49341029 55.41853186 54.73180363 59.13330182 52.64604998
  52.93249568 35.11346806 59.55245157 64.84393564 37.06603994 68.34249874]
 [49.38240126 50.0249187  54.93773084 54.25178994 58.66214161 52.1723612
  52.46205437 34.71434818 59.09327815 64.38244983 36.6753654  67.89076923]
 [50.58688225 51.24983062 56.14407222 55.45892061 59.8912489  53.40545586
  53.69490533 35.97180025 60.32026466 65.62854588 37.95593725 69.13378018]
 [50.46397473 51.09333767 56.01510872 55.32822232 59.74002    53.25861109
  53.54151908 35.67899985 60.14554649 65.45653684 37.64470544 68.94267735]
 [49.18984529 49.82144698 54.74172343 54.0549708  58.46694258 51.98437107
  52.26824425 34.4315

path length [[49.90376689 50.54573643 55.45526802 54.76948867 59.18552992 52.68050966
  52.97004587 35.19394243 59.59739508 64.89291725 37.1586668  68.40560064]
 [50.39047969 51.01534635 55.93834666 55.25179348 59.65808566 53.15725089
  53.4433597  35.59779707 60.0590998  65.35654112 37.55415791 68.85857056]
 [49.81526485 50.42467382 55.35941277 54.67227216 59.06841896 52.57105562
  52.85456544 34.96375396 59.46206387 64.75868784 36.91230232 68.25302321]
 [49.32287621 49.94951089 54.87123751 54.18480922 58.59110757 52.08894955
  52.37593103 34.55248933 58.9956869  64.29075277 36.509859   67.79600752]
 [50.5186144  51.17034863 56.07090936 55.38519973 59.81514786 53.31515277
  53.60235986 35.80492498 60.21732873 65.53175945 37.78424771 69.03620058]
 [50.41432442 51.02768746 55.95781837 55.27051822 59.67691276 53.18613495
  53.46622254 35.53492054 60.05754552 65.37319213 37.49511691 68.85584387]
 [49.1389076  49.75411854 54.68309899 53.99590602 58.40245972 51.91011588
  52.19111077 34.282

path length [[49.84438733 50.46763471 55.39137315 54.70502681 59.11475639 52.60132902
  52.88533904 39.9669193  35.02806494 59.5053404  64.80485852 37.00053982
  68.31083266]
 [50.33935214 50.94420447 55.88173903 55.19469972 59.59350484 53.08637413
  53.36698144 40.42454866 35.44474922 59.97388645 65.27478146 37.40750149
  68.76873895]
 [49.77131176 50.35900971 55.3090171  54.62144876 59.00887999 52.50706395
  52.78499583 39.82849314 34.81905403 59.38218739 64.68189799 36.77305286
  68.16674374]
 [49.27064083 49.87684877 54.81352785 54.12659    58.52534939 52.01661716
  52.29799387 39.36393489 34.39479045 58.90893532 64.20763599 36.35899058
  67.70476611]
 [50.45822842 51.09322989 56.00633128 55.32003321 59.74409074 53.23556357
  53.51749528 40.57543491 35.6408542  60.1254128  65.44345743 37.62653414
  68.94347919]
 [50.37211855 50.96523275 55.90916879 55.22144239 59.61911962 53.12445336
  53.39920754 40.41276075 35.39573373 59.9800133  65.29820572 37.3595898
  68.77316546]
 [49.095605

path length [[45.1579719  49.79551784 50.39378728 55.33603743 54.64911744 40.02199304
  59.04941611 61.1480105  52.5331283  52.80984298 39.86923671 52.05595213
  33.21466953 34.8727556  59.42379815 64.72450104 68.61093957 36.85263927
  68.20916445]
 [45.68103746 50.2985589  50.87766047 55.83364742 55.14612317 40.51174087
  59.5344289  61.65251354 53.02640833 53.2999391  40.33690315 52.54302215
  33.6463283  35.30286374 59.8988447  65.20065942 69.0890618  37.27118441
  68.67267578]
 [45.14626224 49.73773347 50.29837918 55.2672544  54.57926926 39.93857445
  58.95501341 61.08940814 52.4541298  52.72506952 39.74859382 51.96515633
  33.03578123 34.68640448 59.31231753 64.61280342 68.50251381 36.64451365
  68.07480135]
 [44.61692769 49.22896201 49.80887882 54.7644982  54.077054   39.44171025
  58.46519414 60.58021583 51.95541668 52.22957939 39.27392253 51.47261843
  32.59603818 34.24855545 58.83253522 64.13228058 68.02026879 36.21872741
  67.60719115]
 [45.73923947 50.4082774  51.02018158 55

path length [[45.14505241 49.75691828 50.32608533 55.28933482 54.60184571 39.96529046
  58.98975303 61.10746861 52.47586624 52.74474633 39.78393802 51.99229486
  33.09784071 34.73068526 59.35150863 64.65107796 68.53937992 36.71697934
  68.08815617]
 [45.67672793 50.26792365 50.81754173 55.79414199 55.10614521 40.46531023
  59.48108997 61.61889591 52.97733292 53.24338932 40.26126302 52.48734386
  33.54236294 35.1744601  59.83273822 65.13346033 69.02339631 37.14703254
  68.55975178]
 [45.15046228 49.71441494 50.24458482 55.23419317 54.5458137  39.90119775
  58.9070443  61.06213287 52.41225439 52.67593571 39.6806264  51.91632767
  32.94145505 34.56784852 59.2512207  64.55073083 68.44172985 36.52837951
  67.96821326]
 [44.61251537 49.19766073 49.74746849 54.72422096 54.0362851  39.39401847
  58.41087883 60.54600282 51.90532868 52.17186945 39.19623114 51.41578102
  32.48871203 34.11618393 58.76522924 64.06396084 67.95357051 36.0909553
  67.49248447]
 [45.72500448 50.36846938 50.95303345 55.

path length [[45.14206939 49.7318259  55.25620757 54.5682451  39.92745493 58.94357903
  61.08081027 52.43555057 52.69811285 39.72034375 51.94556709 33.00872031
  34.62777074 59.29491933 64.59389886 68.48369917 33.30948597 36.61205287
  68.01256335 63.21369236 43.57105894]
 [45.6809965  50.24958477 55.7671402  55.07875872 40.43610168 59.44034284
  61.5980093  52.94400411 53.20411894 40.20561826 52.44741123 33.46432944
  35.0824218  59.7812948  65.08158313 68.97272467 33.73965153 37.05177284
  68.4902541  63.64600265 43.94973165]
 [45.16208041 49.70244164 55.21280157 54.52411226 39.87984881 58.87099378
  61.04665625 52.38524145 52.64324175 39.63146486 51.88237871 32.87207585
  34.48393097 59.20400798 64.50330674 68.39528456 33.12244248 36.44009268
  67.90373287 63.02636139 43.29920787]
 [44.61688576 49.17892275 54.69669099 54.00835611 39.36401502 58.36938461
  60.52474596 51.87131108 52.13179191 39.13907223 51.37501549 32.4081416
  34.02128278 58.71285048 64.01121688 67.90210052 32.68415

path length [[45.14647515 49.71411711 55.22947385 54.54107018 39.89943035 61.06124248
  52.40348181 52.66073248 39.66519367 51.90614579 32.92990623 66.89445638
  34.54416917 59.24158447 64.54245317 68.43348605 33.20895574 36.51758732
  67.96590831 63.23899064 63.10900472 43.41919084]
 [45.69247651 50.23856123 55.74648119 55.05774929 40.41653151 61.58404055
  52.91888103 53.17407943 40.15811434 52.41473837 33.39663983 67.3996307
  35.00874931 59.73311129 65.03536597 68.9274554  33.64941616 36.96680286
  68.44786142 63.69962782 63.54691965 43.80631936]
 [45.18089923 49.6978702  55.19782266 54.50886208 39.86821862 61.03804464
  52.36655779 52.61994066 39.59035163 51.85578943 32.81339172 66.83663789
  34.41797198 59.16011698 64.46156077 68.35425891 33.03969667 36.36220388
  67.86494435 63.10157856 62.93124298 43.16088338]
 [44.6286395  49.16765917 54.67562751 53.98693013 39.34391158 60.51052946
  51.8456682  52.10113413 39.09027223 51.34166018 32.33824128 66.32717572
  33.94530735 58.66378

path length [[45.15861415 49.70377372 55.20916948 54.52036876 39.88105062 61.04847131
  52.37983596 39.61810667 51.87410331 32.86174933 66.85989212 34.47088007
  59.19582287 64.49659775 68.38851125 33.11670988 36.43181974 67.92743072
  50.9958547  63.15605495 63.00827245 43.27242368 44.7207676  43.93235828]
 [45.71146933 50.23483712 55.73219082 55.04315244 40.40643758 61.57667122
  52.90211374 40.11842751 52.38939073 33.3396258  67.37001421 34.94546302
  59.69228248 64.99467759 68.88737722 33.56758168 36.89051455 68.41288789
  51.45862353 63.62261017 63.45184946 43.66812447 45.10921156 44.29701989]
 [45.20718391 49.70068684 55.18927315 54.50008733 39.8661455  61.03594968
  52.35633107 39.55701342 51.83662026 32.76572944 66.81149957 34.36277872
  59.12349223 64.42537182 68.31845663 32.96571685 36.29321791 67.83293087
  50.86105222 63.02919767 62.84025644 43.02799429 44.46423853 43.63669794]
 [44.64808486 49.16385394 54.66105718 53.97204368 39.3335424  60.50302937
  51.82855372 39.049500

path length [[45.17895151 49.70081357 55.19533037 54.50620076 39.87214707 61.04222739
  39.57876027 51.84948819 32.80434109 66.83028617 34.39905407 59.15853808
  64.45605878 68.3485674  33.03274392 36.35446517 67.89079462 50.91576261
  55.84451267 63.07916287 38.05216217 62.91256812 43.13194461 44.57208423
  43.74247629 51.62285956]
 [45.73844196 50.23842732 55.72429415 55.03501271 40.40566221 61.57564056
  40.08635538 52.37141231 33.29336361 67.34532448 34.88458316 59.65951841
  64.95927116 68.85229999 33.49407398 36.82262232 68.37941408 51.38569138
  56.31977596 63.55160656 38.46773379 63.36180563 43.5362814  44.96911769
  44.1172309  52.01962438]
 [45.24141399 49.71090387 55.1871679  54.49781825 39.87347896 61.04011485
  39.53136409 51.82491198 32.72915557 66.79133424 34.31100008 59.09466346
  64.3945163  68.28770218 32.90036008 36.2328431  67.80209763 50.79377553
  55.73195399 62.96289851 37.84547283 62.75437374 42.90165154 44.32951645
  43.4628285  51.37777415]
 [44.67569951 49.16

path length [[45.20781469 49.70525409 55.18794711 54.49854894 39.87255161 61.04222229
  39.54661705 51.83234687 32.75777701 66.80580557 34.33433341 59.12400859
  64.42070358 68.31356856 32.9576796  36.28564842 67.85925747 50.84280337
  55.77252275 63.00808302 37.9324982  57.46617773 62.82216719 42.99839956
  44.42758844 42.91769764 43.59619282 42.82323941 51.45825894]
 [45.77378595 50.24934797 55.72277499 55.03330166 40.41404012 61.58069354
  40.06152553 52.36084049 33.25796008 67.32569721 34.83047956 59.62912669
  64.92902753 68.82214473 33.42945262 36.76323321 68.35022133 51.31986673
  56.25462691 63.48638193 38.35794254 57.92858096 63.27704674 43.4113973
  44.83339187 43.29755211 43.97889687 43.20438308 51.863391  ]
 [45.28405353 49.7285364  55.19148374 54.50201478 39.89005221 61.05031414
  39.51318731 51.82069396 32.70379427 66.77624856 34.26586529 59.06786531
  64.36888695 68.26192254 32.84414471 36.18117437 67.77479314 50.73372394
  55.67241477 62.90243906 37.7425869  57.33053596

path length [[45.24527314 49.71711818 55.18702443 54.49743233 39.8821308  61.04814413
  39.52146345 51.82271615 32.72193746 66.78653222 34.28856121 59.08528942
  37.31133071 64.39053942 68.28353242 32.89231341 36.22577373 67.82214153
  60.80766262 50.77708605 55.70721498 62.94292315 37.6038955  37.8224262
  57.38987878 62.73741693 42.87278204 44.28998414 42.75934808 43.45706953
  42.67766934 51.33883072 41.03721949 61.05482167]
 [45.81761827 50.26761691 55.72763102 55.03803218 40.43142884 61.59153924
  40.04380834 52.35770843 33.23332664 67.31120892 34.79318287 59.59434163
  37.81369164 64.90395527 68.7969288  33.37444887 36.71271734 68.31631647
  61.30693578 51.26125829 56.19628004 63.42704275 38.0410624  38.25769434
  57.85837324 63.19791288 43.29442549 44.70461979 43.14796542 43.84771652
  43.06720578 51.75010286 41.41274171 61.47519232]
 [45.33526884 49.75359738 55.20221129 54.51268394 39.91570967 61.06627249
  39.50243453 51.82399663 32.68958712 66.76631506 34.2359034  59.0363895


In [ ]:
fd.statistics[-1]

In [ ]:
fd.measured

In [ ]:
fd.measured_upper

In [ ]:
fd.measured_lower

In [ ]:
# pickle.dump(fd.statistics, open("statistics_20" + ".pkl", "wb"))
# pickle.dump(fd.t, open("time_20" + ".pkl", "wb"))
# pickle.dump(fd.measured, open("detectors_20" + ".pkl", "wb"))

In [ ]:
# Plotting standards and Font style
from matplotlib import rc
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
# rc('text', usetex=False)
std_size = 10.  # Size of the plot
fontsize = 10.  # Fontsize in the plot
lw=0.5  # Linewidth
h_length=0.2  # Handle length for the legends
export_dpi = 500  # Dpi for the image export

In [ ]:
# ---------------------------------------------
# Detector light yields
# These are stored in fd.measured
# ---------------------------------------------
# The different detectors (each measuring different wavelengths here)
# wavelengths = {
#     "Detector 1": ["1", "#4575b4"],
#     "Detector 5": ["2", "#91bfdb"],
#     "Detector 8": ["3", "#e0f3f8"],
#     "Detector 3": ["4", "#fee090"],
#     "Detector 10": ["5", "#fc8d59"],
# }
# ---------------------------------------------
figure, (ax1) = plt.subplots(1, 1, figsize=(std_size, std_size * 6. / 8.), sharex=True)
# Plotting the different detector values
# Random noise (e.g. electric)
# noise = {}
# for detector in fd.measured.keys():
#     noise[detector] = np.random.normal(1e3, 2e2, fd.measured[detector].values.shape)
for detector in fd.measured.keys():
    ax1.plot(fd.t,
             fd.measured[detector].values, # + noise[detector],
             lw=lw, label=r"$\mathrm{Channel\;%s}$" % detector) #wavelengths[detector][0], color=wavelengths[detector][1])
# Constructing and plotting the totals
# total = fd.measured["Detector 1"].values + noise[detector]
# for detector in wavelengths.keys():
#     if detector == "Detector 1":
#         continue
#     total += fd.measured[detector].values + noise[detector]
# ax1.plot(fd.t, total, color='k')
# ---------------------------------------------
# Plotting options
ax1.set_xscale('linear')
ax1.set_yscale('log')
ax1.set_xlabel(r'$\mathrm{t}\;[\mathrm{s}]$', fontsize=fontsize)
ax1.set_ylabel(r'$\mathrm{N}$', fontsize=fontsize)
ax1.tick_params(axis = 'both', which = 'major', labelsize=fontsize, direction='in')
ax1.tick_params(axis = 'both', which = 'minor', labelsize=fontsize, direction='in')
h, l = ax1.get_legend_handles_labels()
lgd1 = ax1.legend(h[:3],l[:3], loc=9, bbox_to_anchor=(0.5, +1.27),
                  ncol=3, fontsize=fontsize, handlelength=h_length,
                  fancybox=True, frameon=False)
lgd2 = ax1.legend(h[3:],l[3:], loc=9, bbox_to_anchor=(0.5, +1.17),
                  ncol=3, fontsize=fontsize, handlelength=h_length,
                  fancybox=True, frameon=False)
ax1.add_artist(lgd1)
ax1.set_ylim(1e-8, 1e8)
ax1.set_xlim(0,300)
plt.show()
# ---------------------------------------------
# Storing the image
figure.savefig(PICS + "MC_Example.png",
               bbox_inches='tight', dpi=export_dpi)

In [ ]:
# ---------------------------------------------
# Detector light yields
# These are stored in fd.measured
# ---------------------------------------------
# The different detectors (each measuring different wavelengths here)
# wavelengths = {
#     "Detector 1": ["1", "#4575b4"],
#     "Detector 5": ["2", "#91bfdb"],
#     "Detector 8": ["3", "#e0f3f8"],
#     "Detector 3": ["4", "#fee090"],
#     "Detector 10": ["5", "#fc8d59"],
# }
# ---------------------------------------------
figure, (ax1) = plt.subplots(1, 1, figsize=(std_size, std_size * 6. / 8.), sharex=True)
# Plotting the different detector values
# Random noise (e.g. electric)
# noise = {}
# for detector in fd.measured.keys():
#     noise[detector] = np.random.normal(1e3, 2e2, fd.measured[detector].values.shape)
for detector in fd.measured_upper.keys():
    ax1.plot(fd.t,
             fd.measured_upper[detector].values, # + noise[detector],
             lw=lw, label=r"$\mathrm{Channel\;%s}$" % detector) #wavelengths[detector][0], color=wavelengths[detector][1])
# Constructing and plotting the totals
# total = fd.measured["Detector 1"].values + noise[detector]
# for detector in wavelengths.keys():
#     if detector == "Detector 1":
#         continue
#     total += fd.measured[detector].values + noise[detector]
# ax1.plot(fd.t, total, color='k')
# ---------------------------------------------
# Plotting options
ax1.set_xscale('linear')
ax1.set_yscale('log')
ax1.set_xlabel(r'$\mathrm{t}\;[\mathrm{s}]$', fontsize=fontsize)
ax1.set_ylabel(r'$\mathrm{N}$', fontsize=fontsize)
ax1.tick_params(axis = 'both', which = 'major', labelsize=fontsize, direction='in')
ax1.tick_params(axis = 'both', which = 'minor', labelsize=fontsize, direction='in')
h, l = ax1.get_legend_handles_labels()
lgd1 = ax1.legend(h[:3],l[:3], loc=9, bbox_to_anchor=(0.5, +1.27),
                  ncol=3, fontsize=fontsize, handlelength=h_length,
                  fancybox=True, frameon=False)
lgd2 = ax1.legend(h[3:],l[3:], loc=9, bbox_to_anchor=(0.5, +1.17),
                  ncol=3, fontsize=fontsize, handlelength=h_length,
                  fancybox=True, frameon=False)
ax1.add_artist(lgd1)
ax1.set_ylim(1e-8, 1e8)
ax1.set_xlim(0,300)
plt.show()
# ---------------------------------------------
# Storing the image
figure.savefig(PICS + "MC_Example.png",
               bbox_inches='tight', dpi=export_dpi)

In [ ]:
# ---------------------------------------------
# Detector light yields
# These are stored in fd.measured
# ---------------------------------------------
# The different detectors (each measuring different wavelengths here)
# wavelengths = {
#     "Detector 1": ["1", "#4575b4"],
#     "Detector 5": ["2", "#91bfdb"],
#     "Detector 8": ["3", "#e0f3f8"],
#     "Detector 3": ["4", "#fee090"],
#     "Detector 10": ["5", "#fc8d59"],
# }
# ---------------------------------------------
figure, (ax1) = plt.subplots(1, 1, figsize=(std_size, std_size * 6. / 8.), sharex=True)
# Plotting the different detector values
# Random noise (e.g. electric)
# noise = {}
# for detector in fd.measured.keys():
#     noise[detector] = np.random.normal(1e3, 2e2, fd.measured[detector].values.shape)
for detector in fd.measured_lower.keys():
    ax1.plot(fd.t,
             fd.measured_lower[detector].values, # + noise[detector],
             lw=lw, label=r"$\mathrm{Channel\;%s}$" % detector) #wavelengths[detector][0], color=wavelengths[detector][1])
# Constructing and plotting the totals
# total = fd.measured["Detector 1"].values + noise[detector]
# for detector in wavelengths.keys():
#     if detector == "Detector 1":
#         continue
#     total += fd.measured[detector].values + noise[detector]
# ax1.plot(fd.t, total, color='k')
# ---------------------------------------------
# Plotting options
ax1.set_xscale('linear')
ax1.set_yscale('log')
ax1.set_xlabel(r'$\mathrm{t}\;[\mathrm{s}]$', fontsize=fontsize)
ax1.set_ylabel(r'$\mathrm{N}$', fontsize=fontsize)
ax1.tick_params(axis = 'both', which = 'major', labelsize=fontsize, direction='in')
ax1.tick_params(axis = 'both', which = 'minor', labelsize=fontsize, direction='in')
h, l = ax1.get_legend_handles_labels()
lgd1 = ax1.legend(h[:3],l[:3], loc=9, bbox_to_anchor=(0.5, +1.27),
                  ncol=3, fontsize=fontsize, handlelength=h_length,
                  fancybox=True, frameon=False)
lgd2 = ax1.legend(h[3:],l[3:], loc=9, bbox_to_anchor=(0.5, +1.17),
                  ncol=3, fontsize=fontsize, handlelength=h_length,
                  fancybox=True, frameon=False)
ax1.add_artist(lgd1)
ax1.set_ylim(1e-8, 1e8)
ax1.set_xlim(0,300)
plt.show()
# ---------------------------------------------
# Storing the image
figure.savefig(PICS + "MC_Example.png",
               bbox_inches='tight', dpi=export_dpi)

In [ ]:
# ---------------------------------------------
# Creating a view plot
# This shows the water current and organisms (emitting or not)
# ---------------------------------------------
# The first view plot, this tries to show the individual vortices
figure, (ax1, ax2) = plt.subplots(2, 1, figsize=(std_size, std_size * 6. / 8.), sharex=True)
# ---------------------------------------------
# Constructing the water current grid
courseness = 1000  # The plotting precision
# The grids used for the water current plot
x_grid = np.linspace(0., config['geometry']['volume']['x_length'], courseness)
y_grid = (
    np.linspace(0., config['geometry']['volume']['y_length'], courseness) +
    config['water']['model']['off set'][1]
)
X, Y = np.meshgrid(x_grid, y_grid)
all_points = []
for i in range(0, len(x_grid)):
    all_points.append(np.vstack((X[i], Y[i])).T)
# The water current
x_vel = []
y_vel = []
grad = []
for j in range(0, len(x_grid)):
    # x_vel_tmp, y_vel_tmp, vel_abs = fd._current.velocities(all_points[j], q + config['advanced']['starting step'])
    grad_tmp = fd._current.gradients(all_points[j], 600)
    # x_vel.append(x_vel_tmp)
    # y_vel.append(y_vel_tmp)
    grad.append(grad_tmp)
grad = np.array(grad)
# ---------------------------------------------
# Creating the plots
vmax = 1.
vmin = 0.
# Water current
ax1.imshow(grad.reshape(courseness, courseness), cmap='plasma',
           vmax=vmax, vmin=vmin, extent=[0., 30., 0., 15.])
# The organisms
emission_mask = fd.statistics[-1].loc[:, 'is_emitting']
# Not emitting
ax1.scatter(fd.statistics[-1].loc[~emission_mask, 'pos_x'].values,
            fd.statistics[-1].loc[~emission_mask, 'pos_y'].values,
            color='g',
            s=3.
)
# Emitting
ax1.scatter(fd.statistics[-1].loc[emission_mask, 'pos_x'].values,
            fd.statistics[-1].loc[emission_mask, 'pos_y'].values,
            color='r',
            s=3.
)
# ---------------------------------------------
# Visualizing the detector
# Exclusion
theta = np.linspace(0, 2*np.pi, 50)
r = config['geometry']['exclusion']['radius']  # The detector radius
x1 = r*np.cos(theta)  # The plotting circle x
x2 = r*np.sin(theta)  # The plotting circle y
# The actual detector plot
ax1.plot(x1 + config['geometry']['exclusion']['x_pos'], x2 + config['geometry']['exclusion']['y_pos'],
         lw=lw/2, color='k')
# ---------------------------------------------
# Additional options
ax1.set_ylabel(r'$Y\;[\mathrm{m}]$', fontsize=fontsize)
ax1.tick_params(axis = 'both', which = 'major', labelsize=fontsize)
ax1.tick_params(axis = 'both', which = 'minor', labelsize=fontsize)
#ax1.set_xlim(0., 30.)
#ax1.set_ylim(0., 15.)
# ---------------------------------------------
# The general area where emission is likely visualized
vmax = 0.05
vmin = 0.
# Water current
ax2.imshow(grad.reshape(courseness, courseness), cmap='plasma',
           vmax=vmax, vmin=vmin, extent=[0., 30., 0., 15.])
# The organisms
emission_mask = fd.statistics[-1].loc[:, 'is_emitting']
# Not emitting
ax2.scatter(fd.statistics[-1].loc[~emission_mask, 'pos_x'].values,
            fd.statistics[-1].loc[~emission_mask, 'pos_y'].values,
            color='g',
            s=3.
)
# Emitting
ax2.scatter(fd.statistics[-1].loc[emission_mask, 'pos_x'].values,
            fd.statistics[-1].loc[emission_mask, 'pos_y'].values,
            color='r',
            s=3.
)
# ---------------------------------------------
# Exclusion
theta = np.linspace(0, 2*np.pi, 50)
r = config['geometry']['exclusion']['radius']
x1 = r*np.cos(theta)
x2 = r*np.sin(theta)
ax2.plot(x1 + config['geometry']['exclusion']['x_pos'], x2 + config['geometry']['exclusion']['y_pos'],
         lw=lw/2, color='k')
# ---------------------------------------------
# Additional options
ax2.set_xlabel(r'$X\;[\mathrm{m}]$', fontsize=fontsize)
ax2.set_ylabel(r'$Y\;[\mathrm{m}]$', fontsize=fontsize)
ax2.tick_params(axis = 'both', which = 'major', labelsize=fontsize)
ax2.tick_params(axis = 'both', which = 'minor', labelsize=fontsize)
#ax2.set_xlim(0., 30.)
#ax2.set_ylim(0., 15.)
plt.show()
# ---------------------------------------------
# Storing
figure.savefig(PICS + "MC_Pop.png",
               bbox_inches='tight', dpi=export_dpi)